# Generated by Django 3.0.5 on 2020-04-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('soustitre', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='media/categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='media/marques')),
            ],
        ),
        migrations.CreateModel(
            name='Partenaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='media/partenaires')),
                ('client_ou_fournisseur', models.CharField(choices=[('CL', 'Client'), ('FR', 'Fournisseur')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='media/categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('slug', models.CharField(max_length=70)),
                ('petit_text', models.CharField(blank=True, max_length=200)),
                ('marque', models.CharField(max_length=70)),
                ('logo', models.ImageField(blank=True, upload_to='media')),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('image2', models.ImageField(blank=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, upload_to='media')),
                ('image4', models.ImageField(blank=True, upload_to='media')),
                ('image5', models.ImageField(blank=True, upload_to='media')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='media/produits')),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('recommander', models.BooleanField(default=False)),
                ('caractéristique_1', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_1', models.CharField(blank=True, max_length=100)),
                ('caractéristique_2', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_2', models.CharField(blank=True, max_length=200)),
                ('caractéristique_3', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_3', models.CharField(blank=True, max_length=200)),
                ('caractéristique_4', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_4', models.CharField(blank=True, max_length=200)),
                ('caractéristique_5', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_5', models.CharField(blank=True, max_length=200)),
                ('caractéristique_6', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_6', models.CharField(blank=True, max_length=200)),
                ('caractéristique_7', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_7', models.CharField(blank=True, max_length=200)),
                ('caractéristique_8', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_8', models.CharField(blank=True, max_length=200)),
                ('caractéristique_9', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_9', models.CharField(blank=True, max_length=200)),
                ('caractéristique_10', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_10', models.CharField(blank=True, max_length=200)),
                ('caractéristique_11', models.CharField(blank=True, max_length=100)),
                ('détail_de_caractéristique_11', models.CharField(blank=True, max_length=200)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Categorie')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Marque')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Marque'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Secteur'),
        ),
    ]
